### ISSUE TITLE
Decide on ID schema and ID management for PCL

### ISSUE THREAD

**Issue by dosumis** [obophenotype/provisional_cell_ontology#1]
We currently have IDs like this: 

http://www.jcvi.org/cl_ext/mtg_cluster/pCL54

We should probably move to something that is not specific to some experiment (mtg_cluster) and uses a more conventional padded short_form (PCL_0000054 ?).  

Should we stick with http://www.jcvi.org/cl_ext as the base for now?

#### Options for more conventional PURLs.

1. Request obolibrary membership.

2. Create a PCL domain underneath http://purl.obolibrary.org/obo/CL/ 

This would allow us to use PURL resolution to point to release files like this.
http://purl.obolibrary.org/obo/CL/PCL/pcl.owl

We could use this to roll IDs like this http://purl.obolibrary.org/obo/CL/ PCL/PCL_0000054 - although we don't have any architecture in place to make sure these resolve.

CC @scheuerm @BAevermann

**Comment by shawntanzk** [comment]
Closing as redoing everything using ODK
