### ISSUE TITLE
PCL entry to OBO Foundry 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/provisional_cell_ontology#12]
https://obofoundry.org/faq/how-do-i-register-my-ontology.html 
Shawn to put the MD file on PCL as a PR for everyone to help fill in

**Comment by scheuerm** [comment]
Can you explain what MD and PR mean?

**Comment by scheuerm** [comment]
I definitely want to be involved in the registry process.  Can we discuss this process during our next ontology call?

**Comment by shawntanzk** [comment]
sorry, in my own world >.< MD = markdown, PR = pull request 
These are all here: https://github.com/obophenotype/provisional_cell_ontology/pull/15
I'll add this to the agenda for the next ontology call

**Comment by shawntanzk** [comment]
see https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1708

**Comment by scheuerm** [comment]
Excellent!

--------------------------------------------
Richard H. Scheuermann, Ph.D.
Director, La Jolla Campus
J. Craig Venter Institute
4120 Capricorn Ln.
La Jolla, CA 92037

***@***.******@***.***>
858-200-1876

www.jcvi.org<http://www.jcvi.org>
https://www.jcvi.org/about/richard-scheuermann


From: Shawn Tan ***@***.***>
Reply-To: obophenotype/provisional_cell_ontology ***@***.***>
Date: Monday, January 31, 2022 at 9:28 AM
To: obophenotype/provisional_cell_ontology ***@***.***>
Cc: "Richard H. Scheuermann" ***@***.***>, Comment ***@***.***>
Subject: Re: [obophenotype/provisional_cell_ontology] PCL entry to OBO Foundry (Issue #12)


PCL is now in OBO foundry: https://obofoundry.org/ontology/pcl.html<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fobofoundry.org%2Fontology%2Fpcl.html&data=04%7C01%7Crscheuermann%40jcvi.org%7C8981d5f78a57447ecbd108d9e4df20ee%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637792469256797142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6xEnQE7G1YTjZTJnoqvl%2BxLenUL7pI0Ex%2B%2Frr8WjhnU%3D&reserved=0>
Leaving this ticket open until purls resolve (will probably be a bit more time before it is live on ontobee)

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fobophenotype%2Fprovisional_cell_ontology%2Fissues%2F12%23issuecomment-1026027512&data=04%7C01%7Crscheuermann%40jcvi.org%7C8981d5f78a57447ecbd108d9e4df20ee%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637792469256797142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=HZc0qOe3ZMaC0URvWhWQ6UbYbGJf61Oc3MAm2UEN2pA%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABPP4NHUFUWOJ3FHF6X7QPTUY3BEVANCNFSM5JUFIFKQ&data=04%7C01%7Crscheuermann%40jcvi.org%7C8981d5f78a57447ecbd108d9e4df20ee%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637792469256797142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NAfBr3kUex5MK6PS7tyPuGK%2FKIEHN3uwxykB3XDpZvo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crscheuermann%40jcvi.org%7C8981d5f78a57447ecbd108d9e4df20ee%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637792469256797142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tn9iNeBxK1wZnfbE516TkT%2BMgeoHpQJAUr0RhHw9xN0%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crscheuermann%40jcvi.org%7C8981d5f78a57447ecbd108d9e4df20ee%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637792469256797142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2%2BsdXYGuchwmmBsgoqWJUaEqP5O7uujJ2JmSZnyn15U%3D&reserved=0>.

**Comment by shawntanzk** [comment]
purls now resolve :) everything up and running
