### ISSUE TITLE
Errors after Base Import

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/provisional_cell_ontology#25]
I created a release to check ROBOT report with base file import and a few errors that need to be addressed: 

RO and BFO terms have multiplied labels with `@en` attached, example:
(of note: RO:000053 still has old bearer_of label)
Not sure where this is coming from cause on RO it seems alright

Level | Rule Name | Subject | Property | Value
-- | -- | -- | -- | --
ERROR | multiple_labels | BFO:0000063 | rdfs:label | precedes
ERROR | multiple_labels | BFO:0000063 | rdfs:label | precedes@en
ERROR | multiple_labels | BFO:0000066 | rdfs:label | occurs in
ERROR | multiple_labels | BFO:0000066 | rdfs:label | occurs in@en
ERROR | multiple_labels | BFO:0000067 | rdfs:label | contains process
ERROR | multiple_labels | BFO:0000067 | rdfs:label | contains process@en
ERROR | multiple_labels | RO:0000053 | rdfs:label | bearer of
ERROR | multiple_labels | RO:0000053 | rdfs:label | has characteristic@en
ERROR | multiple_labels | RO:0000056 | rdfs:label | participates in
ERROR | multiple_labels | RO:0000056 | rdfs:label | participates in@en
ERROR | multiple_labels | RO:0000056 | rdfs:label | participates_in

UBERON has some multipled_equivalent_classes error - these are accurate in UBERON itself:

Level | Rule Name | Subject | Property | Value
-- | -- | -- | -- | --
ERROR | multiple_equivalent_classes | UBERON:0000378 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid46142
ERROR | multiple_equivalent_classes | UBERON:0000378 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid46146
ERROR | multiple_equivalent_classes | UBERON:0000483 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid46389
ERROR | multiple_equivalent_classes | UBERON:0000483 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid46393
ERROR | multiple_equivalent_classes | UBERON:0004451 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid55460
ERROR | multiple_equivalent_classes | UBERON:0004451 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid55464
ERROR | multiple_equivalent_classes | UBERON:0015007 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62199
ERROR | multiple_equivalent_classes | UBERON:0015007 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62203
ERROR | multiple_equivalent_classes | UBERON:0015008 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62211
ERROR | multiple_equivalent_classes | UBERON:0015008 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62215
ERROR | multiple_equivalent_classes | UBERON:0018142 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62607
ERROR | multiple_equivalent_classes | UBERON:0018142 | owl:equivalentClass | d80df3fa-9c13-4d2d-a88d-131d173f5c69genid62611

**Comment by shawntanzk** [comment]
Related to #16

**Comment by matentzn** [comment]
Make sure these are fixe wherever they come from, not just in PCL

also use ROBOT 1.8.2 (latest ODK) for generating the report.

Recommendation: do the report check on the base, not the edit file (neither the full ontology)

**Comment by shawntanzk** [comment]
on base file, only error (besides the duplicate_label in gene names and old false CL terms) is that CL:0000881 is missing_label -> on checking the full and edit file, the label is there so don't think its a real problem.

**Comment by matentzn** [comment]
Don't worry about anything else. OBO dashboard looks at base

**Comment by shawntanzk** [comment]
CL:0000881 is a old pcl term - annotations will get cleared when it gets deleted and robot report will clean

**Comment by shawntanzk** [comment]
All local errors fixed
