### ISSUE TITLE
Update native cell (now obsolete) to cell

### ISSUE THREAD

**Issue by dosumis** [obophenotype/provisional_cell_ontology#54]
This is widely used in PCL. All should be updated. Example: https://www.ebi.ac.uk/ols4/ontologies/pcl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FPCL_0019119

**Comment by hkir-dev** [comment]
Fixed with https://github.com/obophenotype/brain_data_standards_ontologies/pull/288 and https://github.com/obophenotype/provisional_cell_ontology/pull/57
