### ISSUE TITLE
Add BDSO as a imported component to PCL

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/provisional_cell_ontology#7]
BDSO should produce an artefact that includes base + custom imports (NS forest markers)
all other imports should come from PCL (CL, NCBITaxon, UBERON)
Blocked until BDSO can produce artefact for PCL

**Comment by hkir-dev** [comment]
[base-ext.owl](https://github.com/obophenotype/brain_data_standards_ontologies/blob/pcl_migration/bdso-base-ext.owl) = base.owl + gene ontologies releaed

**Comment by shawntanzk** [comment]
Fixed with this release https://github.com/obophenotype/provisional_cell_ontology/releases/tag/v2021-12-03
